### ISSUE TITLE
Improve Kwalite Dashboard Projects Tab dependencies feature (MVP)

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#104]
**Current situation**
We already have a concept and a first backend  implementation of the projects tab regarding the dependencies feature: 
See

**How it should be**
We need to optimize the projects tab dependencies feature due to the users needs. 

**Steps**
* [x] present the [dependencies concept](https://github.com/ocr-d/kwalitee-dashboard-back-end/issues/11) and first implementation to Konstantin
* [x] collect further requirements
   * [x] update mechanism
   * [x] JSON schema for the resulting documents
* [x] implement further requirements (defined MVP)

**Acceptance Criteria**
* Implementation meets Konstantins MVP (Review Konstantin)
* backend is prepared for frontend implementation (Review Paul)

**Prior Art**
[dependencies concept](https://github.com/ocr-d/kwalitee-dashboard-back-end/issues/11)
[Pull Request ](https://github.com/OCR-D/kwalitee-dashboard-back-end/pull/14)
