### ISSUE TITLE
Add lacking decision log docu to spec

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#108]
**Current situation**
We decided to place the information in different sections in spec.
* decision log, Web API, Workflow
* decision log contains an overview of decistions (what and why) and links to more detailed documentation in spec
* we already have a draft for that in spec @lena-hinrichsen 
* we collected lacking docu that needs to be provided that way

**User Story**
As a developer and technical user, I would like to have an overview of the current architecture and documentation of key architectural decisions so that I have a better understanding of the architecture and how I can implement OCR-D.

**Steps**

Missing docu: 

- [x] we decided to use Nextflow as a workflow engine, and the whole .nf file (Nextflow file) as the workflow format workflow server and processing server including web API implementation is part of the impl projects (Mehmet, Triet)
- [x] OCR-D Koord provides the Web API spec. Only the REST API wrapper of a single processor is provided by OCR-D Core. (Jonas, Triet)
- [x] [Changes/Upgrades to our tech stack] (https://pad.gwdg.de/zVTkp0B0TOy8FCxkPVHvTg#) (Konstantin) :
** supported python versions
** linux base image
 ** additional libraries/software (MongoDB, uvicorn...) (
- [x] Switch to Slim Containers in ocrd_all (Konstantin)
- [x] Python API changes (Konstantin)

**Acceptance Criteria**

- [x] currently lacking information is provided
- [x] the docu is accessible for all people who might be interested in (public?)

**Prior Art**

- WIP Pad: https://pad.gwdg.de/KRhbnDIbQUikojfPmpaM-g?both
- https://github.com/ocr-d/zenhub/issues/105

**Comment by lena-hinrichsen** [comment]
@kba Can this (and the related issues) be closed or should the Decision Log be more detailed about anything here?

**Comment by kba** [comment]
No, I think this is all covered. Now the hard part is implementing those changes...
