### ISSUE TITLE
OCR-D METS Profile

### ISSUE THREAD

**Issue by lena-hinrichsen** [OCR-D/zenhub#116]
**Current situation**

The Mets file is central for controlling and documenting the individual OCR-D processing steps.

- The digitized files are offered together with the Mets file by the libraries in most cases. A Mets file is also created when digitizing books, for example.
The Mets file of the libraries contains:
    - bibliographic data
    - license data
    - Data on the original
    - Data on the digital version (URLs to the images)

    The structure of the METS file is documented in the ZVDD/DFG viewer profile

- The Mets file of OCR-D contains:
    - OCR-D processing steps

    The structure of the METS file is documented in the OCR-D Mets-Specs.

- The GT labeling scheme can be used to document data related to ground truth. This can also be used in addition to the Mods/Mets schemas. 

**How it should be**
Standardization the OCR-D Mets profile

The standardization of the OCR-D Mets profile aims to:
- Optimization of the OCR-D tools
- Compatibility with the ZVDD/DFG Viewer Profile
- Acceptance and dissemination of the OCR-Mets profile

**Steps**
* [x] collect issues
* [x] Formation of an OCR-D working group 
* [x] Identification of gaps in the specification
* [ ] Coordination and discuss with KIM, standardization
* [ ] Documentation of the specification
* [ ] Implementation of the format in OCR-D
* [ ] Test of the format
* [ ] Rework

**Prior Art**
What has already been done in this regard.
see Pad->https://pad.gwdg.de/J0lMIotHRF2shrKz0hIQLA
