### ISSUE TITLE
OCR-D METS Profile issue collection

### ISSUE THREAD

**Issue by lena-hinrichsen** [OCR-D/zenhub#117]
**Current situation**
For the planned [OCR-D METS Profile](https://github.com/OCR-D/zenhub/issues/116), it is yet unclear what issues shall be resolved before. 

**How it should be**
There should be a prioritised list of already existing issues and PRs.

**Steps**
* [x] have a look at the METS related issues in OCR-D repos
* [x] decide: which issues can be closed/have to be reopened
* [ ] prioritize issues: which ones are important for the OCR-D METS profile

**Prior Art**
PR, issues etc, e.g. 
- https://github.com/OCR-D/spec/pull/207
- https://github.com/OCR-D/spec/issues/86

**Comment by tboenig** [comment]
## Look:
- **METS Profile** relevant collection (problems, solutions and proposals, aspects for handling ocr-d (core) mets...): https://pad.gwdg.de/J0lMIotHRF2shrKz0hIQLA?view#Collection
