### ISSUE TITLE
Make GT levels actionable for scripts

### ISSUE THREAD

**Issue by kba** [OCR-D/zenhub#28]
# Current situation

We have our very detailled GT Guidelines which contain tables of replacements for glyphs in the three levels of encoding accuracy. To implement these rules in code however, developers need to create their own rulesets from this data.

# How it should be

It would be beneficial to have these rules in an easy-to-parse format like JSON to use in GT tooling. Instead of every developer creating their own rules, we can share a common set of rules to improve interoperability and consistency.

# Steps
* [x] Develop and provide all possible rules for level estimation along the lines of Calamari ruleset.
* [ ] Develop a mechanism for rules beyond simple character replacement (such as regular expressions)
* [ ] Define a JSON Schema for rulesets
* [ ] Discuss conceptually in GT call and technically in Tech Call
* [ ] Integrate into GT Guidelines maintenance and release workflow

# Prior Art

* https://github.com/uniwue-zpd/PAGETools/tree/main/pagetools/resources/rulesets
* https://github.com/tboenig/gt-guidelines/tree/master/rulesets (this is the template or example)
* https://github.com/tboenig/gt-guidelines/tree/gh-pages/rules (this is the current status!)
