### ISSUE TITLE
Set up GWDG Git LFS for OCR-D

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#29]
- [x] Konstantin and Matthias prepare the Repo
- [x] Konstantin set up lfs on the ground truth server
- [x] Triet sets up lfs connection
- [x] gwdg gitlab accounts to kbt boenig

**Comment by krvoigt** [comment]
waiting for Mathias to ensure that it works.

**Comment by krvoigt** [comment]
@kba Triet is waiting for the github repo. pls inform him when it is done. Maybe you can link something to this issue.

**Comment by kba** [comment]
OK, repo set up at https://github.com/OCR-D/git-lfs-test, Matthias and Triet have admin rights.

**Comment by tdoan2010** [comment]
I've already set up the LFS connection to GWDG GitLab. A README file is also added to the project.
