### ISSUE TITLE
Common understanding about the workflow requirements

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#48]
As a team, we need a summary of the past discussion and the resulting requirements so that we can discuss them together and generate our next steps from them. 

- [x] summary of the past discussion @cneud 
- [x] questions regarding higher level requirements @tdoan2010 
- [x] discussion meeting @krvoigt 
- [x] basic requirements list https://pad.gwdg.de/AosGiphcQoKKIqoRYBqK-A

**Comment by kba** [comment]
* Old WF repo: https://github.com/OCR-D/ocrd-workflows
* Old WF format: https://github.com/OCR-D/spec/pull/171
* Wiki on WF Guide and recommendations: 
* WF Server: https://github.com/OCR-D/core/pull/652
* Ocrd Controller: https://github.com/bertsky/ocrd_controller
* RFC: Preloading OCR-D Processors: https://hackmd.io/23-JzLp_Q96cb6T0ttoFIA

**Comment by cneud** [comment]
> summary of the past discussion

The aim for a workflow component for OCR-D goes back to the initial phase I of the project. I'll try to summarize the high level discussions so far.

A strength of OCR-D lies in its modularity and flexibility in the use of _Processors_, with often more than one _Processor_ being available for a given task (or [step](https://ocr-d.de/en/workflows)). Experiences, tests and user expectations have conveyed that - due to the complex and very diverse nature of the documents to be processed - often only tailor made workflows can guarantee the optimal result quality. 

The OCR-D [functional model](https://ocr-d.de/assets/Funktionsmodell.svg) shows that OCR is always composed from a sequence of such steps, with the condition that the output (image, text or metadata) from a single _Processor_ must also be made available for subsequent _Processors_ to make use of (theoretically, also loops are conceivable). 

In practice, workflows are often specific to an institution or project, composed of ad-hoc solutions or local scripts and lacking standardized interfaces, descriptions and documentation. This greatly hinders reuse, comparability and replicability. 

So far we can summarize the following needs, or rather benefits, of a standardized workflow management component:
- standardized workflows should **support the transparent exchange of information between _Processors_ on a global level**
- standardized workflows should **ease the composition of sequences from a diverse range of _Processors_**
- standardized workflows should **provide better means for replicability, evaluation and comparison**
- standardized workflows should **help with the reuse of exisiting workflows by others**
- standardized workflows should **capture provenance output that can aid in debugging and optimization**

A bit further down the line, standardized workflows could also be used for discovery (i.e. finding an appropriate workflow for a set of documents), or to dynamically compose sequences of _Processors_ merely based on a workflow description.

Other aspects that could greatly benefit from standardized workflows are **scalability/parallelization** (e.g. while some steps require more time to complete, other steps could potentially already be started and run in parallel to reduce the overall execution time) and **error handling/robustness** (i.e. the ability to overcome exceptions or crashes of _Processors_ without stopping the overall workflow execution). 

A first steps towards standardized workflows was made with 

> Old WF repo: https://github.com/OCR-D/ocrd-workflows

which basically encapsulates workflows as a simple sequence of _Processors_ in Posix shell scripts. This has a few drawbacks e.g. with regard to the validation of the sequence and the data exchange between _Processors_ (see also the example and explanation in the [wiki](https://github.com/OCR-D/ocrd-website/wiki/Intro-workflows) on workflows), or the capture of global provenance information. 

> Old WF format: https://github.com/OCR-D/spec/pull/171

tries to specify a standardized format for such workflows and also has a good discussion of the [benefits/drawbacks](https://github.com/OCR-D/spec/pull/171) of this approach, while also touching on alternatives like [CWL](https://www.commonwl.org/user_guide/). [Note: while initially also [Taverna](https://incubator.apache.org/projects/taverna.html) was a candidate, with it being retired as an Apache incubator early in 2020, we eventually discarded it)]

> WF Server: https://github.com/OCR-D/core/pull/652

is an implementation of a workflow server based on https://github.com/OCR-D/spec/pull/171 that already aims to overcome some of the problems in parallelization and error recovery that are well explained under

> RFC: Preloading OCR-D Processors: https://hackmd.io/23-JzLp_Q96cb6T0ttoFIA

Last but not least, another relevant piece of software in this context is 

> Ocrd Controller: https://github.com/bertsky/ocrd_controller

which provides a network interface (via SSH) for executing _Processors_ based on a local installation of [ocrd_all](https://github.com/OCR-D/ocrd_all), and which could be exposed to third party software such as e.g. Kitodo.

**Comment by krvoigt** [comment]
we need concrete requirements. There is a difference between workflow requirements and requirements of the processors.
we need to provide an excample workflow and ask IMPL for agreement. Triet will take one OCR-D example and put it in NextFlow.
