### ISSUE TITLE
Implement Workflow Examples for discussion

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#55]
As a OCR-D developer I want to implement a workflow to present it to other project partners to have a discussion basis and a basic list of requirements.

AC: 
- [x] simple sequence of OCR-D processors with Nextflow
- [x] simple sequence of OCR-D processors with CWL
- [x]  parallel workflow (pseudo page-wise processing) with Nextflow
- [x] parallel workflow (pseudo page-wise processing) with CWL
