### ISSUE TITLE
Review the CWL and Nextflow Workflows

### ISSUE THREAD

**Issue by lena-hinrichsen** [OCR-D/zenhub#62]
- [x] collect pros and cons for domain specific language (Nextflow) vs a descriptive yaml text format (CWL)
- [x] compare the formats
- [x] improve the list of required features

**Comment by MehmedGIT** [comment]
The example workflows are here: https://github.com/MehmedGIT/OPERANDI_TestRepo/tree/master/ExampleWorkflows

**Comment by lena-hinrichsen** [comment]
I think, this can be closed @MehmedGIT  ?

**Comment by MehmedGIT** [comment]
@lena-hinrichsen Yes.

**Comment by lena-hinrichsen** [comment]
decision: We use Nextflow
