### ISSUE TITLE
Collect and implement feedback regarding the WebAPI

### ISSUE THREAD

**Issue by mweidling** [OCR-D/zenhub#79]
- [x] anouncement (after merge) in Lobby
- [x] make IMPL aware of API
- [x] present in TechCall 
- [x] session @ workshop
- [ ] maybe bilateral calls

**Comment by lena-hinrichsen** [comment]
- [x] anouncement (after merge) in Lobby
- [x] make IMPL aware of API
- [x] present in TechCall 
- [x] session @ workshop
- [x] maybe bilateral calls

**Comment by krvoigt** [comment]
[This](https://pad.gwdg.de/Ldx-Ay1JRXO1iUROxJDeIw) is the protocol of our meeting. In short, we agreed that:

All implementation projects agree to use Nextflow.
Therefore, Nextflow scripting language (Groovy) can be used as an exchange format.
OCR-D/core will provide a tool to validate the workflow.
Validating means that the workflows must not contain script task, but only call to ocrd- processors.
We need to check https://github.com/OCR-D/core/pull/652 and decide what to do with it.
OCR-D/core needs to provide a mechanism so that all processors can expose their REST endpoints.

**Comment by mweidling** [comment]
Is there anything more to be done here after the workshop?

**Comment by lena-hinrichsen** [comment]
> Is there anything more to be done here after the workshop?

No, I'll close :-)
