### ISSUE TITLE
Refine the Kwalite dashboard requirements regarding projects tab

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#95]
**Describe the feature you'd like**

We need a clear idea about the next steps regarding the projects tab of the kwalite dashboard. 
kwalite dashboard consists of thee tabs: Projects, Workflows and Processors. We agreed that we should focus on the projects tab first, because:
1. this is Konstantins starting point, when he implemented the tool...it is easy to go on here.
2. as koordination project we need to check our repos/projects for quality cireria, to enable us to decide which projects/repos belong to our product.

**Is your feature request related to a problem? Please describe.**
We currently have no clear requirements list.
We need 
- [x]  digging deeper into the code of the current implementation to get an better understanding of the code base to enable us to generate an idea about how to go on with further implementation;  AC: first next steps regarding implementation
- [x] a list of requirements, a prioritisation, a definition of mvp. AC: self explaining
- [x] a mock up of the projects tab as discussion basis AC: self explaining
- [x] clone or move the kwalite tool to the official ocr-d organisation in github

**User story**
As a a koord developer I need clearer requirements in order to start implementing helpful features in the sense of code quality and in view of our product definition.

**Additional context**
This feature helps us meeting our requirements regarding code quality and product definition

**Comment by krvoigt** [comment]
https://pad.gwdg.de/y41n80-BR3yq2LtUsBl-8w?both
