### ISSUE TITLE
Preparing the Backend for Implementation

### ISSUE THREAD

**Issue by krvoigt** [OCR-D/zenhub#97]
- [x] detachment of the backend from the kwalitee application
- [x] automation of the updates of the json file
- [x] extend json (ocr-d release)
